var vfed = {
	'vfed': {
		'head': '各大视频网站资源采集',
		'tips': 'vfed主题推荐采集资源',
		'rows': [{
			'name': '1717云资源',
			'rema': '含VIP视频',
			'apis': 'http://zy.itono.cn/inc/api.php',
			'flag': 'yiqi',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '6U云资源',
			'rema': '含VIP视频',
			'apis': 'http://zy.ataoju.com/inc/api.php',
			'flag': 'liuu',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '强强云资源',
			'rema': '含VIP视频,有暗链',
			'apis': 'http://caiji.000o.cc/inc/api.php',
			'flag': 'qiang',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'CKFLV云资源',
			'rema': '不推荐,各种无图,tu.php无效',
			'apis': 'http://zy.vivcms.com/inc/api.php',
			'flag': 'ckflv',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'TV6云资源',
			'rema': '不推荐,各种无图,tu.php无效',
			'apis': 'http://cj.tv6.com/mox/inc/api.php',
			'flag': 'tvliu',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}]
	},
	'advs': {
		'head': '广告投放 >>> 官方QQ群：<a href="https://jq.qq.com/?_wv=1027&k=5UIPDzc">137183109</a> >>> 业务QQ：<a href="http://wpa.qq.com/msgrd?v=3&uin=1570457334&site=qq&menu=yes">1570457334</a> >>>',
		'tips': '',
		'rows': [{
			'name': '超清无广告解析',
			'rema': '支持https',
			'apis': 'https://jx.itaoju.top/?url=',
			'tip1': '优酷演示',
			'url1': 'https://jx.itaoju.top/?url=https://v.youku.com/v_show/id_XMjkzNzY0NzkyOA==.html',
			'tip2': '腾讯演示',
			'url2': 'https://jx.itaoju.top/?url=https://v.qq.com/x/cover/5r3n1td1xijy87h.html',
			'tip3': '奇艺演示',
			'url3': 'https://jx.itaoju.top/?url=https://www.iqiyi.com/v_19rrdmuvuc.html',
			'tip4': '搜狐演示',
			'url4': 'https://jx.itaoju.top/?url=https://www.le.com/ptv/vplay/31078847.html',
			'tips': 'ok',
			'sell': '1'
		}]
	},
	'offi': {
		'head': '视频网站专区',
		'tips': '',
		'rows': [{
			'name': 'PPTV资源',
			'rema': 'CKFLV云资源',
			'apis': 'http://zy.vivcms.com/inc/pptv.php',
			'flag': 'ckflv',
			'coll': 'pptv',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '优酷资源',
			'rema': 'CKFLV云资源',
			'apis': 'http://zy.vivcms.com/inc/youku.php',
			'flag': 'ckflv',
			'coll': 'youku',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '乐视资源',
			'rema': 'CKFLV云资源',
			'apis': 'http://zy.vivcms.com/inc/letv.php',
			'flag': 'ckflv',
			'coll': 'letv',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '奇艺资源',
			'rema': 'CKFLV云资源',
			'apis': 'http://zy.vivcms.com/inc/qiyi.php',
			'flag': 'ckflv',
			'coll': 'qiyi',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '腾讯资源',
			'rema': 'CKFLV云资源',
			'apis': 'http://zy.vivcms.com/inc/qq.php',
			'flag': 'ckflv',
			'coll': 'qq',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '芒果资源',
			'rema': 'CKFLV云资源',
			'apis': 'http://zy.vivcms.com/inc/mgtv.php',
			'flag': 'ckflv',
			'coll': 'mgtv',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '搜狐资源',
			'rema': 'CKFLV云资源',
			'apis': 'http://zy.vivcms.com/inc/sohu.php',
			'flag': 'ckflv',
			'coll': 'sohu',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'PPTV资源',
			'rema': 'TV6云资源',
			'apis': 'http://cj.tv6.com/mox/inc/pptv.php',
			'flag': 'tvliu',
			'coll': 'pptv',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '优酷资源',
			'rema': 'TV6云资源',
			'apis': 'http://cj.tv6.com/mox/inc/youku.php',
			'flag': 'tvliu',
			'coll': 'youku',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '芒果资源',
			'rema': 'TV6云资源',
			'apis': 'http://cj.tv6.com/mox/inc/mgtv.php',
			'flag': 'tvliu',
			'coll': 'mgtv',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '奇艺资源',
			'rema': 'TV6云资源',
			'apis': 'http://cj.tv6.com/mox/inc/qiyi.php',
			'flag': 'tvliu',
			'coll': 'qiyi',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '腾讯资源',
			'rema': 'TV6云资源',
			'apis': 'http://cj.tv6.com/mox/inc/qq.php',
			'flag': 'tvliu',
			'coll': 'qq',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '搜狐资源',
			'rema': 'TV6云资源',
			'apis': 'http://cj.tv6.com/mox/inc/sohu.php',
			'flag': 'tvliu',
			'coll': 'sohu',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}]
	},
	'comp': {
		'head': '综合资源专区',
		'tips': '',
		'rows': [{
			'name': '最大云资源',
			'rema': 'https资源',
			'apis': 'http://www.zdziyuan.com/inc/s_api.php',
			'flag': 'zuida',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '最新云资源',
			'rema': 'https资源',
			'apis': 'http://api.zuixinapi.com/inc/api.php',
			'flag': 'zuixin',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '最快云资源',
			'rema': '不支持https',
			'apis': 'http://cj.zuikzy.com/inc/api.php',
			'flag': 'zuikuai',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '极速云资源',
			'rema': 'https资源',
			'apis': 'http://www.caijizy.com/inc/api.php',
			'flag': 'jisu',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '酷酷云资源',
			'rema': 'https资源',
			'apis': 'http://www.kuyun9.com/inc/s_ldg_m3u8.asp',
			'flag': 'kuku',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '酷播云资源',
			'rema': 'https资源',
			'apis': 'http://api.kbzyapi.com/inc/s_api.php',
			'flag': 'kubo',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '百万云资源',
			'rema': 'https资源',
			'apis': 'http://www.baiwanzy.com/inc/api.php',
			'flag': 'baiwan',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '永久云资源',
			'rema': 'https资源',
			'apis': 'http://www.yongjiuzy.com/inc/s_api.php',
			'flag': 'yongjiu',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '帝国云资源',
			'rema': 'https资源',
			'apis': 'http://www.yszydg.com/inc/api.php',
			'flag': 'diguo',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '暧昧云资源',
			'rema': 'https资源',
			'apis': 'http://www.imeizy.com/inc/api.php',
			'flag': 'aimei',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '资源片资源',
			'rema': 'https资源',
			'apis': 'http://www.ziyuanpian.com/inc/api.php',
			'flag': 'ziyuan',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '几千客资源',
			'rema': 'https资源',
			'apis': 'http://www.go1977.com/inc/api.php',
			'flag': 'qianke',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '605云资源',
			'rema': 'https资源',
			'apis': 'http://www.605zy.cc/inc/api.php',
			'flag': 'liuzy',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '129云资源',
			'rema': '不支持https',
			'apis': 'http://www.129zy.com/inc/api.php',
			'flag': 'yierjiu',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'OK云资源',
			'rema': 'https资源,有暗链',
			'apis': 'http://api.iokzy.com/inc/api1s.php',
			'flag': 'okzy',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '精品云资源',
			'rema': 'https资源',
			'apis': 'http://www.jingpinzy.com/inc/s_api.php',
			'flag': 'jingpin',
			'coll': 'all',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}]
	},
	'm3u8': {
		'head': '切片资源专区',
		'tips': '',
		'rows': [{
			'name': '最大云资源',
			'rema': 'https资源',
			'apis': 'http://www.zdziyuan.com/inc/s_api_zuidam3u8.php',
			'flag': 'zuida',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '最新云资源',
			'rema': 'https资源',
			'apis': 'http://api.zuixinapi.com/inc/apixinm3u8.php',
			'flag': 'zuixin',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '最快云资源',
			'rema': '不支持https',
			'apis': 'http://cj.zuikzy.com/inc/zkm3u8.php',
			'flag': 'zuikuai',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '极速云资源',
			'rema': 'https资源',
			'apis': 'http://www.caijizy.com/inc/jsm3u8.php',
			'flag': 'jisu',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '酷酷云资源',
			'rema': 'https资源',
			'apis': 'http://www.kuyun9.com/inc/s_ldg_kkm3u8.asp',
			'flag': 'kuku',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '酷播云资源',
			'rema': 'https资源',
			'apis': 'http://api.kbzyapi.com/inc/s_api_kakam3u8.php',
			'flag': 'kubo',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '百万云资源',
			'rema': 'https资源',
			'apis': 'http://www.baiwanzy.com/inc/bwm3u8.php',
			'flag': 'baiwan',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '永久云资源',
			'rema': 'https资源',
			'apis': 'http://www.yongjiuzy.com/inc/s_yjm3u8.php',
			'flag': 'yongjiu',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '帝国云资源',
			'rema': 'https资源',
			'apis': 'http://www.yszydg.com/inc/apickm3u8.php',
			'flag': 'diguo',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '暧昧云资源',
			'rema': 'https资源',
			'apis': 'http://www.imeizy.com/inc/apim3u8.php',
			'flag': 'aimei',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '资源片资源',
			'rema': 'https资源',
			'apis': 'http://www.ziyuanpian.com/inc/ckm3u8.php',
			'flag': 'ziyuan',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '几千客资源',
			'rema': 'https资源',
			'apis': 'http://www.go1977.com/inc/gom3u8.php',
			'flag': 'qianke',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '605云资源',
			'rema': 'https资源',
			'apis': 'http://www.605zy.cc/inc/605m3u8.php',
			'flag': 'liuzy',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '129云资源',
			'rema': '不支持https',
			'apis': 'http://www.129zy.com/inc/129m3u8.php',
			'flag': 'yierjiu',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'OK云资源',
			'rema': 'https资源,有暗链',
			'apis': 'http://api.iokzy.com/inc/apickm3u8s.php',
			'flag': 'okzy',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '精品云资源',
			'rema': 'https资源',
			'apis': 'http://www.jingpinzy.com/inc/s_api_jpm3u8.php',
			'flag': 'jingpin',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}]
	},
	'play': {
		'head': '云播资源专区',
		'tips': '',
		'rows': [{
			'name': '最大云资源',
			'rema': 'https资源',
			'apis': 'http://www.zdziyuan.com/inc/s_api_zuidall.php',
			'flag': 'zuida',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '最新云资源',
			'rema': 'https资源',
			'apis': 'http://api.zuixinapi.com/inc/apixinyun.php',
			'flag': 'zuixin',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '最快云资源',
			'rema': '不支持https',
			'apis': 'http://cj.zuikzy.com/inc/zkyun.php ',
			'flag': 'zuikuai',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '极速云资源',
			'rema': 'https资源',
			'apis': 'http://www.caijizy.com/inc/jsyun.php',
			'flag': 'jisu',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '酷酷云资源',
			'rema': 'https资源',
			'apis': 'http://www.kuyun9.com/inc/s_ldg_kkyun.asp',
			'flag': 'kuku',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '酷播云资源',
			'rema': 'https资源',
			'apis': 'http://api.kbzyapi.com/inc/s_api_kuyun.php',
			'flag': 'kubo',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '百万云资源',
			'rema': 'https资源',
			'apis': 'http://www.baiwanzy.com/inc/bwyun.php',
			'flag': 'baiwan',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '永久云资源',
			'rema': 'https资源',
			'apis': 'http://www.yongjiuzy.com/inc/s_yjyun.php',
			'flag': 'yongjiu',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '帝国云资源',
			'rema': 'https资源',
			'apis': 'http://www.yszydg.com/inc/apikuyun.php',
			'flag': 'diguo',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '暧昧云资源',
			'rema': 'https资源',
			'apis': 'http://www.imeizy.com/inc/apikuyun.php',
			'flag': 'aimei',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '资源片资源',
			'rema': 'https资源',
			'apis': 'http://www.ziyuanpian.com/inc/kuyun.php',
			'flag': 'ziyuan',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '几千客资源',
			'rema': 'https资源',
			'apis': 'http://www.go1977.com/inc/link.php',
			'flag': 'qianke',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '605云资源',
			'rema': 'https资源',
			'apis': 'http://www.605zy.cc/inc/605yun.php',
			'flag': 'liuzy',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '129云资源',
			'rema': '不支持https',
			'apis': 'http://www.129zy.com/inc/129zy.php',
			'flag': 'yierjiu',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'OK云资源',
			'rema': 'https资源,有暗链',
			'apis': 'http://api.iokzy.com/inc/apikuyuns.php',
			'flag': 'okzy',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '老爷云资源',
			'rema': '不支持https',
			'apis': 'http://www.88laoye.com/inc/api.php',
			'flag': 'laoye',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'C值云资源',
			'rema': '不支持https',
			'apis': 'http://www.czhiziyuan.com/inc/api.php',
			'flag': 'czhi',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}]
	},
	'down': {
		'head': '下载资源专区',
		'tips': '',
		'rows': [{
			'name': '最大云资源',
			'rema': '迅雷下载',
			'apis': 'http://www.zdziyuan.com/inc/s_apidown.php',
			'flag': 'zuida',
			'coll': 'down',
			'tips': 'ok',
			'sell': '',
			'down': '&param=JmN0PTE'
		}, {
			'name': '精品云资源',
			'rema': '迅雷下载',
			'apis': 'http://www.jingpinzy.com/inc/apidown.php',
			'flag': 'jingpin',
			'coll': 'down',
			'tips': 'ok',
			'sell': '',
			'down': '&param=JmN0PTE'
		}]
	},
	'fuck': {
		'head': '叉站资源专区',
		'tips': '',
		'rows': [{
			'name': '哥搞妹资源',
			'rema': 'M3U8,不支持https',
			'apis': 'http://gegaomeizy2.com/inc/api.php',
			'flag': 'gegaomei',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '色色云资源',
			'rema': 'M3U8,不支持https',
			'apis': 'http://sscj8.com/inc/api.php',
			'flag': 'sese',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '撸死你资源',
			'rema': 'M3U8,不支持https',
			'apis': 'http://lsnzxcj.com/inc/api.php',
			'flag': 'lusini',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '玖玖云资源',
			'rema': 'M3U8,不支持https',
			'apis': 'http://99zxcj.com/inc/api.php',
			'flag': 'jiujiu',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'YELLOW资源',
			'rema': 'M3U8,不支持https',
			'apis': 'http://zmwcj8.com/inc/api.php',
			'flag': 'yellow',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'IXX云资源',
			'rema': 'M3U8,不支持https',
			'apis': 'http://api.iixxzyapi.com/inc/api.php',
			'flag': 'ixx',
			'coll': 'm3u8',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': '九州云资源',
			'rema': '云播,https资源',
			'apis': 'http://zyapi.jssida.top/api.php',
			'flag': 'jiuzhou',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}, {
			'name': 'BT616资源',
			'rema': '云播,不支持https',
			'apis': 'http://www.bt616.com/inc/api.php',
			'flag': 'btliu',
			'coll': 'line',
			'tips': 'ok',
			'sell': '',
			'down': ''
		}]
	}
};
var html = '';
var urls = 'api?ac={ac}&rday={rday}&cjflag={flag}&cjurl={apis}';
$.each(vfed, function(list, name) {
	html += '<table class="layui-table"><thead>';
	html += '<tr><td colspan="7"><span style="float:left">' + name.head + '</span><span style="float:right">' + name.tips + '</span></td></tr>';
	html += '</thead><tbody>';
	$.each(name.rows, function(nums, info) {
		var nums = parseInt(nums) + 1;
		if(nums < 10) nums = '0' + nums;
		var url1 = urls.replace('{ac}', 'list').replace('{rday}', '').replace('{flag}', info.flag).replace('{apis}', info.apis);
		var url2 = urls.replace('{ac}', 'cjday').replace('{rday}', '24').replace('{flag}', info.flag).replace('{apis}', info.apis);
		var url3 = urls.replace('{ac}', 'cjday').replace('{rday}', '98').replace('{flag}', info.flag).replace('{apis}', info.apis);
		var url4 = urls.replace('{ac}', 'cjall').replace('{rday}', '').replace('{flag}', info.flag).replace('{apis}', info.apis);
		html += '<tr>';
		html += '<td width="20" align="center">' + nums + '</td>';
		if(info.tips == 'ok') var tips = '<span class="layui-badge layui-bg-green">正常</span>';
		else var tips = '<span class="layui-badge">异常</span>';
		html += '<td width="40" align="center">' + tips + '</td>';
		var sell = '';
		if(info.sell == '1') var sell = '<span class="layui-badge">推荐</span>';
		if(list == 'advs') {
			html += '<td><a target="_blank" href="' + info.apis + '">' + info.name + '【' + info.rema + '】' + sell + '</a></td>';
			html += '<td width="60" align="center"><a target="_blank" href="' + info.url1 + '">' + info.tip1 + '</a></td></td>';
			html += '<td width="60" align="center"><a target="_blank" href="' + info.url2 + '">' + info.tip2 + '</a></td>';
			html += '<td width="60" align="center"><a target="_blank" href="' + info.url3 + '">' + info.tip3 + '</a></td>';
			html += '<td width="60" align="center"><a target="_blank" href="' + info.url4 + '">' + info.tip4 + '</a></td>';
		} else {
			html += '<td><a href="' + url1 + info.down + '">' + info.name + '【' + info.rema + '】' + sell + '</a></td>';
			html += '<td width="60" align="center"><a href="javascript:;" class="timming" data-name="当日采集：' + encodeURIComponent(info.name + '【' + info.rema + '】') + '" data-flag="' + encodeURIComponent(info.flag + info.coll) + '" data-param="' + url2.replace('api?', '') + info.down + '">定时任务</a></td>';
			html += '<td width="60" align="center"><a href="' + url2 + info.down + '">采集当天</a></td>';
			html += '<td width="60" align="center"><a href="' + url3 + info.down + '">采集本周</a></td>';
			html += '<td width="60" align="center"><a href="' + url4 + info.down + '">采集所有</a></td>';
		}
		html += '</tr>';
	});
	html += '</tbody></table>';
});
document.write(html);
$('.timming').click(function() {
	if(confirm('确认添加到定时任务吗？')) {
		$.post('../../../template/vfed/asset/fed/create.php?id=tim', 'name=' + $(this).attr('data-name') + '&flag=' + $(this).attr('data-flag') + '&param=' + encodeURIComponent($(this).attr('data-param')), function(data) {
			alert(data.msg);
		}).error(function() {
			alert('请求失败');
		}, 'json');
	}
});